#!/usr/bin/env python

import django.core.wsgi
import os
import sys


# GETTING-STARTED: make sure the next line points to your settings.py:
os.environ['DJANGO_SETTINGS_MODULE'] = 'BealsTreasure_Project.settings'

# GETTING-STARTED: make sure the next line points to your django project dir:
sys.path.append(
    os.path.join(os.environ['OPENSHIFT_REPO_DIR'],
                 'wsgi',
                 'BealsTreasure_Project'))

virtenv = os.environ['APPDIR'] + '/virtenv/'

# GETTING-STARTED: make sure the next line has the right python version:
os.environ['PYTHON_EGG_CACHE'] = os.path.join(
    virtenv,
    'lib/python2.7/site-packages')

virtualenv = os.path.join(virtenv, 'bin/activate_this.py')

try:
    execfile(virtualenv, dict(__file__=virtualenv))
except:
    pass

application = django.core.wsgi.get_wsgi_application()
